using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Warehouse.Application.Abstractions;
using Warehouse.Application.Alarms;
using Warehouse.Application.Audit;
using Warehouse.Application.Documents;
using Warehouse.Application.Inventory;
using Warehouse.Application.Options;
using Warehouse.Application.Realtime;
using Warehouse.Domain;
using Warehouse.Domain.Entities;
using Warehouse.Domain.Validation;

namespace Warehouse.Application.Gates;

/// <summary>One completed read session submitted by a handheld or on-reader app.</summary>
public sealed record DeviceSessionRequest
{
    /// <summary>Gate the device is operating. Must already exist.</summary>
    public required string GateCode { get; init; }

    /// <summary>Device identity, e.g. the reader's serial. Registered on first use.</summary>
    public required string DeviceId { get; init; }

    /// <summary>Distinct EPCs the device observed. The server de-duplicates again regardless.</summary>
    public required IReadOnlyList<string> DetectedEpcs { get; init; }

    public DateTimeOffset? StartedAt { get; init; }

    public DateTimeOffset? CompletedAt { get; init; }

    /// <summary>Raw reads before the device de-duplicated. Diagnostic only.</summary>
    public int RawReadCount { get; init; }

    /// <summary>False if the device reported a reader fault during the session.</summary>
    public bool ReaderHealthy { get; init; } = true;

    /// <summary>
    /// Idempotency key generated by the device. Re-submitting the same key
    /// returns the original verdict instead of moving stock twice.
    /// </summary>
    public string? SessionKey { get; init; }
}

public sealed record DeviceSessionResult
{
    public required string CycleId { get; init; }

    public required bool Passed { get; init; }

    public required string Summary { get; init; }

    public required string DocumentNumber { get; init; }

    public required DocumentStatus DocumentStatus { get; init; }

    public int ExpectedCount { get; init; }

    public int DetectedCount { get; init; }

    public IReadOnlyList<string> Matched { get; init; } = [];

    public IReadOnlyList<string> Missing { get; init; } = [];

    public IReadOnlyList<string> Unknown { get; init; } = [];

    public IReadOnlyList<string> Unexpected { get; init; } = [];

    public IReadOnlyList<string> Alarms { get; init; } = [];

    public int MovedArticles { get; init; }

    public int MovedQuantity { get; init; }

    public int BalanceArticles { get; init; }

    public int BalanceQuantity { get; init; }

    /// <summary>True when the submission was a replay and no stock moved again.</summary>
    public bool WasReplay { get; init; }
}

public interface IDeviceSessionService
{
    Task<DeviceSessionResult> SubmitAsync(
        int documentId,
        DeviceSessionRequest request,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Accepts a read session performed by an app running on the reader itself.
/// </summary>
/// <remarks>
/// The on-reader app validates locally so the operator gets an immediate
/// "this roll is not on the document" while the load is still in front of them.
/// That local check is a courtesy, not the decision: this service re-runs the
/// same <see cref="IValidationEngine"/> against the database and is the only
/// thing that can move stock. A device that lies, lags or runs an old EPC list
/// cannot talk the warehouse into accepting a bad movement.
///
/// Everything downstream is shared with the GPIO-driven path -- same engine,
/// same transactional commit, same alarms, same audit trail -- so a movement
/// recorded from a handheld is indistinguishable in the ledger from one
/// recorded at a fixed gate.
/// </remarks>
public sealed class DeviceSessionService(
    IWarehouseDbContext db,
    IClock clock,
    INumberGenerator numbers,
    IValidationEngine validator,
    IInventoryService inventory,
    IAlarmService alarms,
    IAuditService audit,
    IGateNotifier notifier,
    IOptionsMonitor<GateOptions> gateOptions,
    ILogger<DeviceSessionService> logger) : IDeviceSessionService
{
    public async Task<DeviceSessionResult> SubmitAsync(
        int documentId,
        DeviceSessionRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);

        var document = await db.Documents
            .Include(d => d.Items)
            .FirstOrDefaultAsync(d => d.Id == documentId, cancellationToken)
            .ConfigureAwait(false)
            ?? throw new WarehouseValidationException($"Document {documentId} was not found.");

        var gate = await db.Gates.FirstOrDefaultAsync(g => g.Code == request.GateCode, cancellationToken)
            .ConfigureAwait(false)
            ?? throw new WarehouseValidationException($"Gate {request.GateCode} was not found.");

        if (gate.Direction is { } allowed && allowed != document.Type)
        {
            throw new WarehouseValidationException($"Gate {gate.Code} only handles {allowed} movements.");
        }

        // The replay check comes before every other guard on purpose. A device
        // whose network dropped after the server committed will retry, and by
        // then the document may well be Completed. Checking status first would
        // answer that retry with an error about a movement that in fact
        // succeeded, and the operator would rescan a load that is already in.
        var triggerKey = string.IsNullOrWhiteSpace(request.SessionKey)
            ? $"{gate.Code}|{request.DeviceId}|{clock.UtcNow.ToUnixTimeMilliseconds()}"
            : $"{gate.Code}|{request.DeviceId}|{request.SessionKey}";

        var existing = await db.GateCycles
            .FirstOrDefaultAsync(c => c.TriggerKey == triggerKey, cancellationToken)
            .ConfigureAwait(false);

        if (existing is not null)
        {
            logger.LogInformation(
                "Device session {Key} already processed as {CycleId}; returning original verdict",
                triggerKey, existing.CycleId);

            return await ReplayAsync(existing, document, cancellationToken).ConfigureAwait(false);
        }

        if (document.Status is DocumentStatus.Cancelled or DocumentStatus.Completed)
        {
            throw new WarehouseValidationException(
                $"Document {document.DocumentNumber} is {document.Status} and cannot be scanned.");
        }

        var reader = await ResolveReaderAsync(request.DeviceId, gate, cancellationToken).ConfigureAwait(false);

        var expected = document.Items
            .Where(i => !i.IsDetected)
            .Select(i => i.Epc)
            .ToHashSet(Epc.Comparer);

        var detected = request.DetectedEpcs
            .Select(Epc.Normalize)
            .Where(e => e.Length > 0)
            .Distinct(Epc.Comparer)
            .ToList();

        var known = await db.EpcTags
            .Where(t => detected.Contains(t.Epc))
            .Select(t => new { t.Epc, t.IsActive, t.Status })
            .ToListAsync(cancellationToken)
            .ConfigureAwait(false);

        var knownSet = known.Select(k => k.Epc).ToHashSet(Epc.Comparer);

        var blocked = known
            .Where(k => !k.IsActive || k.Status is EpcStatus.Retired or EpcStatus.Blocked)
            .Select(k => k.Epc)
            .ToHashSet(Epc.Comparer);

        var options = gateOptions.CurrentValue;

        var result = validator.Validate(new ValidationInput
        {
            DocumentType = document.Type,
            ExpectedEpcs = expected,
            DetectedEpcs = detected,
            KnownEpcs = knownSet,
            BlockedEpcs = blocked,
            ReaderHealthy = request.ReaderHealthy,
            Policy = new ValidationPolicy
            {
                RequireAllExpected = options.RequireAllExpected,
                FailOnUnknown = options.FailOnUnknownEpc,
                FailOnUnexpected = options.FailOnUnexpectedEpc,
                FailOnEmpty = options.FailOnEmptyRead,
                RequireHealthyReader = options.RequireHealthyReader,
                MaxEpcsPerCycle = options.MaxEpcsPerCycle
            }
        });

        var now = clock.UtcNow;

        var cycle = new GateCycle
        {
            CycleId = await numbers.NextCycleIdAsync(cancellationToken).ConfigureAwait(false),
            TriggerKey = triggerKey,
            GateId = gate.Id,
            ReaderId = reader.Id,
            DocumentId = document.Id,
            Status = result.IsPass ? GateCycleStatus.Passed : GateCycleStatus.Failed,
            StartedAt = request.StartedAt ?? now,
            CompletedAt = request.CompletedAt ?? now,
            DetectedEpcCount = result.DetectedCount,
            RawReadCount = request.RawReadCount,
            ExpectedEpcCount = result.ExpectedCount,
            UnknownEpcCount = result.Unknown.Count,
            UnexpectedEpcCount = result.Unexpected.Count,
            MissingEpcCount = result.Missing.Count,
            ValidationResult = result.Outcome,
            ValidationSummary = result.Summary,
            ReaderHealthy = request.ReaderHealthy
        };

        db.GateCycles.Add(cycle);

        AddCycleEpcs(cycle, result);

        if (document.Status == DocumentStatus.Draft || document.GateId is null)
        {
            document.GateId = gate.Id;
            document.Status = DocumentStatus.InProgress;
            document.ReleasedAt ??= now;
        }

        audit.Enlist(new AuditEntry
        {
            Action = AuditAction.GateCycleStarted,
            GateId = gate.Id,
            DocumentId = document.Id,
            DocumentNumber = document.DocumentNumber,
            CycleId = cycle.CycleId,
            ReaderId = reader.Id,
            Result = $"device session from {request.DeviceId}, {result.DetectedCount} EPCs"
        });

        await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

        var moved = 0;
        var movedQuantity = 0;

        if (result.IsPass)
        {
            var commit = await inventory.CommitCycleAsync(new InventoryCommitRequest
            {
                GateCycleId = cycle.Id,
                CycleId = cycle.CycleId,
                DocumentId = document.Id,
                MatchedEpcs = result.Matched,
                GateId = gate.Id
            }, cancellationToken).ConfigureAwait(false);

            moved = commit.MovedArticles;
            movedQuantity = commit.MovedQuantity;
        }
        else
        {
            await RaiseAlarmsAsync(gate, reader, document, cycle, result, cancellationToken)
                .ConfigureAwait(false);
        }

        var fresh = await db.Documents
            .AsNoTracking()
            .FirstAsync(d => d.Id == document.Id, cancellationToken)
            .ConfigureAwait(false);

        await NotifyAsync(gate.Code, cycle, fresh, result, cancellationToken).ConfigureAwait(false);

        logger.LogInformation(
            "Device session {CycleId} on {GateCode} for {DocumentNumber}: {Summary}",
            cycle.CycleId, gate.Code, document.DocumentNumber, result.Summary);

        return new DeviceSessionResult
        {
            CycleId = cycle.CycleId,
            Passed = result.IsPass,
            Summary = result.Summary,
            DocumentNumber = fresh.DocumentNumber,
            DocumentStatus = fresh.Status,
            ExpectedCount = result.ExpectedCount,
            DetectedCount = result.DetectedCount,
            Matched = result.Matched,
            Missing = result.Missing,
            Unknown = result.Unknown,
            Unexpected = result.Unexpected,
            Alarms = result.Alarms.Select(a => a.ToString()).ToList(),
            MovedArticles = moved,
            MovedQuantity = movedQuantity,
            BalanceArticles = fresh.BalanceArticles,
            BalanceQuantity = fresh.BalanceQuantity
        };
    }

    /// <summary>
    /// Finds the reader row for a device, registering it on first contact.
    /// A reader that turns up in the field should appear in the dashboard, not
    /// be rejected for not having been typed in first.
    /// </summary>
    private async Task<Reader> ResolveReaderAsync(
        string deviceId,
        Gate gate,
        CancellationToken cancellationToken)
    {
        var reader = await db.Readers.FirstOrDefaultAsync(r => r.ReaderId == deviceId, cancellationToken)
            .ConfigureAwait(false);

        if (reader is not null)
        {
            reader.LastSeenAt = clock.UtcNow;
            reader.IsOnline = true;

            return reader;
        }

        reader = new Reader
        {
            ReaderId = deviceId,
            Name = deviceId,
            GateId = gate.Id,
            Model = "Chainway U300 (on-device app)",
            IsActive = true,
            IsOnline = true,
            LastSeenAt = clock.UtcNow,
            ConnectedAt = clock.UtcNow
        };

        db.Readers.Add(reader);
        await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

        logger.LogInformation("Registered on-device reader {DeviceId} on gate {GateCode}", deviceId, gate.Code);

        return reader;
    }

    private void AddCycleEpcs(GateCycle cycle, ValidationResult result)
    {
        void Add(IEnumerable<string> epcs, EpcClassification classification)
        {
            foreach (var epc in epcs)
            {
                db.GateCycleEpcs.Add(new GateCycleEpc
                {
                    GateCycle = cycle,
                    Epc = epc,
                    Classification = classification,
                    ReadCount = classification == EpcClassification.Missing ? 0 : 1,
                    FirstSeenAt = classification == EpcClassification.Missing ? null : clock.UtcNow,
                    LastSeenAt = classification == EpcClassification.Missing ? null : clock.UtcNow
                });
            }
        }

        Add(result.Matched, EpcClassification.Expected);
        Add(result.Unknown, EpcClassification.Unknown);
        Add(result.Unexpected, EpcClassification.Unexpected);
        Add(result.Missing, EpcClassification.Missing);
    }

    private async Task RaiseAlarmsAsync(
        Gate gate,
        Reader reader,
        Document document,
        GateCycle cycle,
        ValidationResult result,
        CancellationToken cancellationToken)
    {
        var requests = result.Alarms.Select(alarm =>
        {
            var (message, epc, list) = alarm switch
            {
                AlarmType.UnknownEpc => (
                    $"Unknown EPC read at {gate.Code}. {result.Unknown.Count} tag(s) are not registered.",
                    result.Unknown.FirstOrDefault(), (IReadOnlyList<string>)result.Unknown),

                AlarmType.UnexpectedEpc => (
                    $"EPC read at {gate.Code} does not belong to {document.DocumentNumber}. "
                        + $"{result.Unexpected.Count} tag(s) rejected.",
                    result.Unexpected.FirstOrDefault(), (IReadOnlyList<string>)result.Unexpected),

                AlarmType.MissingEpc => (
                    $"Incomplete movement at {gate.Code}. Expected {result.ExpectedCount}, "
                        + $"read {result.DetectedCount}, missing {result.Missing.Count}.",
                    result.Missing.FirstOrDefault(), (IReadOnlyList<string>)result.Missing),

                AlarmType.NoEpc => (
                    $"No EPC read at {gate.Code}. An item may have passed without a tag.",
                    null, (IReadOnlyList<string>)[]),

                AlarmType.ReaderError => (
                    $"The reader at {gate.Code} reported a fault during the session.",
                    null, (IReadOnlyList<string>)[]),

                _ => ($"Validation failed at {gate.Code}: {result.Summary}",
                    null, (IReadOnlyList<string>)[])
            };

            return new RaiseAlarmRequest
            {
                AlarmType = alarm,
                Message = message,
                GateId = gate.Id,
                GateCode = gate.Code,
                DocumentId = document.Id,
                DocumentNumber = document.DocumentNumber,
                GateCycleId = cycle.Id,
                CycleId = cycle.CycleId,
                ReaderId = reader.Id,
                Epc = epc,
                Epcs = list
            };
        }).ToList();

        if (requests.Count > 0)
        {
            await alarms.RaiseManyAsync(requests, cancellationToken).ConfigureAwait(false);
        }
    }

    private async Task<DeviceSessionResult> ReplayAsync(
        GateCycle cycle,
        Document document,
        CancellationToken cancellationToken)
    {
        var epcs = await db.GateCycleEpcs
            .AsNoTracking()
            .Where(e => e.GateCycleId == cycle.Id)
            .ToListAsync(cancellationToken)
            .ConfigureAwait(false);

        IReadOnlyList<string> By(EpcClassification c) =>
            epcs.Where(e => e.Classification == c).Select(e => e.Epc).ToList();

        return new DeviceSessionResult
        {
            CycleId = cycle.CycleId,
            Passed = cycle.ValidationResult == ValidationOutcome.Pass,
            Summary = cycle.ValidationSummary ?? string.Empty,
            DocumentNumber = document.DocumentNumber,
            DocumentStatus = document.Status,
            ExpectedCount = cycle.ExpectedEpcCount,
            DetectedCount = cycle.DetectedEpcCount,
            Matched = By(EpcClassification.Expected),
            Missing = By(EpcClassification.Missing),
            Unknown = By(EpcClassification.Unknown),
            Unexpected = By(EpcClassification.Unexpected),
            BalanceArticles = document.BalanceArticles,
            BalanceQuantity = document.BalanceQuantity,
            WasReplay = true
        };
    }

    private async Task NotifyAsync(
        string gateCode,
        GateCycle cycle,
        Document document,
        ValidationResult result,
        CancellationToken cancellationToken)
    {
        try
        {
            await notifier.CycleCompletedAsync(new CycleCompletedUpdate
            {
                GateCode = gateCode,
                CycleId = cycle.CycleId,
                Passed = result.IsPass,
                DocumentNumber = document.DocumentNumber,
                DocumentStatus = document.Status,
                ExpectedCount = result.ExpectedCount,
                DetectedCount = result.DetectedCount,
                Missing = result.Missing,
                Unknown = result.Unknown,
                Unexpected = result.Unexpected,
                Summary = result.Summary,
                Timestamp = clock.UtcNow
            }, cancellationToken).ConfigureAwait(false);
        }
        catch (Exception ex)
        {
            // A dashboard that missed the update must not fail the movement.
            logger.LogWarning(ex, "Could not broadcast device session {CycleId}", cycle.CycleId);
        }
    }
}
