<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Warehouse.Application/Warehouse.Application.csproj" />
    <ProjectReference Include="../../src/Warehouse.Infrastructure/Warehouse.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Warehouse.Rfid.Simulation/Warehouse.Rfid.Simulation.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>
</Project>
