namespace Warehouse.Domain.Entities;

/// <summary>
/// A planned movement: the authoritative list of EPCs expected to cross a
/// gate in one direction (§4).
/// </summary>
public class Document
{
    public int Id { get; set; }

    /// <summary>Generated by the database, e.g. "IN-2026-000001" (§5).</summary>
    public string DocumentNumber { get; set; } = string.Empty;

    public DocumentType Type { get; set; }

    public DocumentStatus Status { get; set; } = DocumentStatus.Draft;

    /// <summary>Operator the document is issued to; shown on the gate display.</summary>
    public int? UserId { get; set; }
    public User? User { get; set; }

    /// <summary>Denormalised for the gate display so it renders without a join.</summary>
    public string? UserDisplayName { get; set; }

    /// <summary>Gate this document is released to. Null while Draft.</summary>
    public int? GateId { get; set; }
    public Gate? Gate { get; set; }

    public string? Reference { get; set; }

    public string? Notes { get; set; }

    /// <summary>Count of expected articles. Maintained with <see cref="Items"/>.</summary>
    public int ExpectedArticles { get; set; }

    /// <summary>Sum of expected unit quantities.</summary>
    public int ExpectedQuantity { get; set; }

    /// <summary>Articles confirmed across all passed cycles.</summary>
    public int DetectedArticles { get; set; }

    public int DetectedQuantity { get; set; }

    /// <summary>Articles still outstanding. Drives the gate display's balance panel.</summary>
    public int BalanceArticles => Math.Max(0, ExpectedArticles - DetectedArticles);

    public int BalanceQuantity => Math.Max(0, ExpectedQuantity - DetectedQuantity);

    public int RetryCount { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset? ReleasedAt { get; set; }

    public DateTimeOffset? CompletedAt { get; set; }

    public DateTimeOffset? CancelledAt { get; set; }

    public string? CancelledReason { get; set; }

    public byte[]? RowVersion { get; set; }

    public ICollection<DocumentItem> Items { get; set; } = [];
    public ICollection<GateCycle> Cycles { get; set; } = [];
}

/// <summary>One expected EPC line on a document.</summary>
public class DocumentItem
{
    public long Id { get; set; }

    public int DocumentId { get; set; }
    public Document Document { get; set; } = null!;

    public long EpcTagId { get; set; }
    public EpcTag EpcTag { get; set; } = null!;

    /// <summary>
    /// Copy of the EPC string. Denormalised deliberately: the validation engine
    /// loads expected EPCs by document without touching the tag table, which
    /// keeps a gate cycle to a single indexed read.
    /// </summary>
    public string Epc { get; set; } = string.Empty;

    public int Quantity { get; set; } = 1;

    /// <summary>Set once the EPC has been confirmed by a passed cycle.</summary>
    public bool IsDetected { get; set; }

    public DateTimeOffset? DetectedAt { get; set; }

    /// <summary>Cycle that confirmed this line.</summary>
    public long? DetectedByCycleId { get; set; }
}
